appname/config/routes.rb
Rails.application.routes.draw do
  root to: "admin#index"
  resources :companies
  resources :employees
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html  
end

appname/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

appname/app/models/company.rb
class Company < ApplicationRecord
    has_many :employees
    belongs_to :user
end

appname/app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :company 

end

appname/app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :companies
end

appname/app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :require_login
    layout 'admin'
    def index
    end
end

appname/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

appname/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_login
  before_action :set_company, only: %i[ show edit update destroy ]
  layout 'admin'
  # GET /companies or /companies.json
  def index
    @companies = Company.all 
  end  

  def show
  end  

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company branch was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company branch was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company branch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:id, :name, :address, :user_id)
    end
end

appname/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_login
  before_action :set_employee, only: %i[ show edit update destroy ]
  layout 'admin'
  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  
  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:id, :num_employee, :private_num, :name, :email, :position, :status, :company_id)
    end
  end
  
end
  

appname/app/helpers/application_helper.rb
module ApplicationHelper
end

appname/app/views/admin/index.html.erb
<br>
<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

<!-- Three columns of text below the carousel -->
<div class="row">
    <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->


<!-- START THE FEATURETTES -->

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
    </div>
    <div class="col-md-5">
        <svg   svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
    </div>
    <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
    </div>
    <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

    </div>
</div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->

</div><!-- /.container -->

appname/app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation"> 
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3">
    <div class="col-12">
      <label for="inputName" class="form-label">Nombre de la Sucursal</label>
      <%= form.text_field :name, :class => "form-control" %>
    </div>

    <div class="col-12">
      <label for="inputAddress" class="form-label">Domicilio de la Sucursal</label>
      <%= form.text_field :address, :class => "form-control" %>
    </div>

    <div class="actions col-12">
      <% if action_name=="edit" %>
          <%= form.submit "Actualizar Sucursal", :class => "btn btn-primary" %>
        <% else %>
          <%= form.submit "Crear Sucursal", :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>

<% end %>

appname/app/views/companies/edit.html.erb
<div class="container-md">
    <h1>Editar Sucursal</h1>

    <%= render 'form', company: @company %>

    <%= link_to 'Mostrar', @company %> |
    <%= link_to 'Regresar', companies_path %>
</div>

appname/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-10">
      <h1>Sucursales Registradas</h1>
    </div>
    <div class="col">
      <%= link_to 'Nueva Sucursal', new_company_path, :class => "btn btn-primary" %>
    </div>
  </div>
</div>

<br>

<div class="container-md">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Nombre</th>
          <th scope="col">Direccion</th>
          <th scope="col">Mostrar</th>
          <th scope="col">Editar</th>
          <th scope="col">Eliminar</th>
        </tr>  
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.id %></td>
            <td><%= company.name %></td>
            <td><%= company.address %></td>
            <td><%= link_to image_tag('visibility.svg'), company %></td>
            <td><%= link_to image_tag('edit.svg'), edit_company_path(company) %></td>
            <td><%= link_to image_tag('delete.svg'), company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>  
      </tbody>
    </table>
  </div>
</div>

appname/app/views/companies/new.html.erb
<div class="container-md">
    <h1>Nueva Sucursal</h1>

    <br>

    <%= render 'form', company: @company %> 
    <br> 
    <%= link_to 'Regresar', companies_path %> 
</div> 

appname/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-md">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Sucursal</th>
                    <th scope="col">Direccion</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @company.id %></td>
                    <td><%= @company.name %></td>
                    <td><%= @company.address %></td>
                </tr>
            </tbody>
        </table>
    </div>
    <%= link_to 'Regresar', companies_path %>
</div>

appname/app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3">
  
    <div class="col-12">
      <label for="inputAddress" class="form-label">Numero de Empleado</label>      
      <%= form.number_field :num_employee, :class => "form-control"%>
    </div>

    <div class="col-12">
      <label for="inputAddress2" class="form-label">Numero Privado</label>      
      <%= form.number_field :private_num, :class => "form-control" %>
    </div>
    
    <div class="col-md-6">
      <label for="inputEmail4" class="form-label">Nombre</label>      
      <%= form.text_field :name, :class => "form-control" %>
    </div>

    <div class="col-md-6">
      <label for="inputPassword4" class="form-label">Email</label>      
      <%= form.text_field :email, :class => "form-control" %>
    </div>

    <div class="col-12">
      <label for="inputAddress2" class="form-label">Posición</label>      
      <%= form.text_field :position, :class => "form-control" %>
    </div>

    <div class="col-6">
      <label for="inputAddress3" class="form-label">Compañia</label>      
      <%= form.collection_select( "company_id", Company.all,:id, :name, {:include_blank => false},{:class => "form-control"} ) %>
    </div>

    <div class="col-6">
      <div class="form-check">        
        <%= form.check_box :status, :class => "form-check-input" %>
        <label class="form-check-label" for="gridCheck">
          Estatus Activo
        </label>
      </div>
    </div>

    <div class="actions col-12">      
      <% if action_name=="edit"  %>          
        <%= form.submit "Actualizar empleado", :class => "btn btn-primary" %>
      <% else %>
        <%= form.submit "Crear empleado", :class => "btn btn-primary" %>         
      <% end %>
    </div>
  </div>
<% end %>

appname/app/views/employees/edit.html.erb
<div class="container-md">
    <h1>Editing Employee</h1>
    <br>
    <%= render 'form', employee: @employee %>
    <br>
    <%= link_to 'Mostrar', @employee, :class => "btn btn-primary" %>    
</div>

appname/app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-10"><h1>Employees</h1></div>
    <div class="col"><%= link_to 'New Employee', new_employee_path, :class => "btn btn-primary" %></div>
  </div>
</div>
<br>
<div class="container-md">
  <div class="table-responsive" >
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Num employee</th>
          <th scope="col">Private num</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Position</th>
          <th scope="col">Status</th>
          <th scope="col">Mostrar</th>
          <th scope="col">Editar</th>
          <th scope="col">Eliminar</th>
        </tr>
      </thead>
      <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <td><%= employee.id %></td>
            <td><%= employee.num_employee %></td>
            <td><%= employee.private_num %></td>
            <td><%= employee.name %></td>
            <td><%= employee.email %></td>
            <td><%= employee.position %></td>
            <td><%= employee.status %></td>
            <td><%= link_to image_tag('visibility.svg'), employee %></td>
            <td><%= link_to image_tag('edit.svg'), edit_employee_path(employee) %></td>
            <td><%= link_to image_tag('delete.svg'), employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<div>

appname/app/views/employees/new.html.erb
<div class="container-md">
    <h1>Nuevo Empleado</h1>
    <br>
    <%= render 'form', employee: @employee %>
    <br>    
</div>

appname/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-3"><strong>Id:</strong></div>
    <div class="col-3"><%= @employee.id %></div>
  
    <div class="col-3"><strong>Num employee:</strong></div>
    <div class="col-3"><%= @employee.num_employee %></div>

    <div class="col-3"><strong>Private num:</strong></div>
    <div class="col-3"><%= @employee.private_num %></div>

    <div class="col-3"><strong>Name:</strong></div>
    <div class="col-3"><%= @employee.name %></div>

    <div class="col-3"><strong>Email:</strong></div>
    <div class="col-3"><%= @employee.email %></div>

    <div class="col-3"><strong>Position:</strong></div>
    <div class="col-3"><%= @employee.position %></div>

    <div class="col-3"><strong>Status:</strong></div>
    <div class="col-3"><%= @employee.status %></div>

    <div class="col-3"><strong>compañia:</strong></div>
    <div class="col-3"><%= @employee.company_id %></div>
  </div>
  <br>
  <%= link_to 'Editar', edit_employee_path(@employee), :class => "btn btn-primary" %>
  <%= link_to 'Volver', employees_path, :class => "btn btn-primary" %>
</div>

appname/app/views/layouts/_header.html.erb
<header>
  <nav class="back-blue black large-padding">
    <ul class="row center-xs" style="list-style: none;">
      <li class="col-md">            
        <%= link_to 'Home', root_path, :class => 'text-light' %>
      </li>

      <li class="col-md">
        <%= link_to "Employees", employees_path, :class => 'text-light' %>
      </li>

      <li class="col-md">
        <%= link_to 'Company Branch', companies_path, :class => 'text-light' %>  
      </li>

      <li class="col-md text-light">
        Reports
      </li>
      
      <li class="col-md text-light">
        IMG
      </li>
      
      <li class="col-md text-light">
        <% if signed_in? %>
          Signed in as: <%= current_user.email %>
          <li class="col-md">
            <%= button_to 'Sign out', sign_out_path, method: :delete, :class => 'btn btn-link text-warning' %>
          </li>                    
        <% else %>
          <%= link_to 'Sign in', sign_in_path, :class => 'btn btn-link' %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

appname/app/views/layouts/admin.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>Foo Corp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'employees', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
    <div id="flash" class="container-md text-center text-danger">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>

</html>

appname/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>Company Branch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'employees', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    
    <%= render 'employees/header'%>
    
    <br>
    <%= yield %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>

</html>

appname/app/views/users/_form.html.erb
<div class="my-3 form-floating">    
  <%= form.text_field :email, type: 'email', :class => 'form-control' %>
  <label for="floatingInput">Correo Electrónico</label>
</div>

<div class="my-3 form-floating">    
  <%= form.password_field :password, :class => 'form-control'%>
  <label for="floatingPassword">Password</label>
</div>

<div class="checkbox mb-3">
  <label>
    <input type="checkbox" value="remember-me"> Remember me
  </label>
</div>

appname/app/views/users/new.html.erb
<div id="clearance" class="form-signin text-center ">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>

    <div class="container-md w-50 my-5">
      <%= render partial: '/users/form', object: form %>

      <div class="my-3 submit-field">
        <%= form.submit 'Sign Up', :class => 'w-50 btn btn-lg btn-primary' %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div> 
    </div>    

  <% end %>
</div>